import JSZip from "jszip";

export const DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
export const XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
export const WORD_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
export const SHEET_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
export const CHART_NS = "http://schemas.openxmlformats.org/drawingml/2006/chart";
export const REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
export const PACKAGE_NS = "http://schemas.openxmlformats.org/package/2006/relationships";
export const TYPE_NS = "http://schemas.openxmlformats.org/package/2006/content-types";
export const rels = (relations: string) => `<Relationships xmlns="${PACKAGE_NS}">${relations}</Relationships>`;
export const relation = (id: string, type: string, target: string, external = false) => `<Relationship Id="${id}" Type="${REL_NS}/${type}" Target="${target}"${external ? ' TargetMode="External"' : ""}/>`;

export async function wordVisualFixture() {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", `<Types xmlns="${TYPE_NS}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/header.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/></Types>`);
  zip.file("_rels/.rels", rels(relation("main", "officeDocument", "word/document.xml")));
  zip.file("word/_rels/document.xml.rels", rels(relation("header", "header", "header.xml") + relation("link", "hyperlink", "https://example.invalid/private", true)));
  zip.file("word/document.xml", `<w:document xmlns:w="${WORD_NS}" xmlns:r="${REL_NS}"><w:body><w:p><w:r><w:t>VISUAL WORD BODY</w:t></w:r></w:p><w:p><w:fldSimple w:instr="DDEAUTO unsafe command"><w:r><w:t>STORED FIELD 73</w:t></w:r></w:fldSimple></w:p><w:p><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText>INCLUDETEXT &quot;https://example.invalid/private&quot;</w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>CACHED COMPLEX FIELD</w:t></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p><w:p><w:hyperlink r:id="link"><w:r><w:t>Readable hyperlink label</w:t></w:r></w:hyperlink></w:p><w:tbl><w:tblPr/><w:tblGrid><w:gridCol w:w="3000"/><w:gridCol w:w="3000"/></w:tblGrid><w:tr><w:tc><w:p><w:r><w:t>LEFT CELL</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>RIGHT CELL</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:sectPr><w:headerReference w:type="default" r:id="header"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720"/></w:sectPr></w:body></w:document>`);
  zip.file("word/header.xml", `<w:hdr xmlns:w="${WORD_NS}"><w:p><w:r><w:t>HEADER V42</w:t></w:r></w:p></w:hdr>`);
  return zip.generateAsync({ type: "nodebuffer" });
}

export async function sheetVisualFixture() {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", `<Types xmlns="${TYPE_NS}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/><Override PartName="/xl/charts/chart1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawingml.chart+xml"/></Types>`);
  zip.file("_rels/.rels", rels(relation("main", "officeDocument", "xl/workbook.xml")));
  zip.file("xl/workbook.xml", `<s:workbook xmlns:s="${SHEET_NS}" xmlns:r="${REL_NS}"><s:bookViews><s:workbookView/></s:bookViews><s:sheets><s:sheet name="Cached results" sheetId="1" r:id="sheet"/></s:sheets><s:definedNames><s:definedName name="Danger">WEBSERVICE("https://example.invalid/private")</s:definedName></s:definedNames><s:calcPr calcMode="auto" fullCalcOnLoad="1"/></s:workbook>`);
  zip.file("xl/_rels/workbook.xml.rels", rels(relation("sheet", "worksheet", "worksheets/sheet1.xml")));
  zip.file("xl/worksheets/sheet1.xml", `<s:worksheet xmlns:s="${SHEET_NS}" xmlns:r="${REL_NS}"><s:dimension ref="A1:D20"/><s:sheetViews><s:sheetView workbookViewId="0"/></s:sheetViews><s:sheetFormatPr defaultRowHeight="18"/><s:cols><s:col min="1" max="4" width="24" customWidth="1"/></s:cols><s:sheetData><s:row r="1"><s:c r="A1" t="inlineStr"><s:is><s:t>Alpha</s:t></s:is></s:c><s:c r="B1"><s:f>1+1</s:f><s:v>73</s:v></s:c></s:row><s:row r="2"><s:c r="A2" t="inlineStr"><s:is><s:t>Beta</s:t></s:is></s:c><s:c r="B2"><s:v>19</s:v></s:c></s:row><s:row r="3"><s:c r="B3"><s:f>NOW()</s:f></s:c></s:row><s:row r="4"><s:c r="B4" t="str"><s:f>WEBSERVICE("https://example.invalid/private")</s:f><s:v>=LITERAL CACHED STRING</s:v></s:c></s:row></s:sheetData><s:conditionalFormatting sqref="B1"><s:cfRule type="expression" priority="1"><s:formula>NOW()</s:formula></s:cfRule></s:conditionalFormatting><s:pageMargins left="0.4" right="0.4" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><s:drawing r:id="drawing"/></s:worksheet>`);
  zip.file("xl/worksheets/_rels/sheet1.xml.rels", rels(relation("drawing", "drawing", "../drawings/drawing1.xml")));
  zip.file("xl/drawings/drawing1.xml", `<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL_NS}"><xdr:twoCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>6</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>4</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>20</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="2" name="Cached chart"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm><a:graphic><a:graphicData uri="${CHART_NS}"><c:chart xmlns:c="${CHART_NS}" r:id="chart"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor></xdr:wsDr>`);
  zip.file("xl/drawings/_rels/drawing1.xml.rels", rels(relation("chart", "chart", "../charts/chart1.xml")));
  zip.file("xl/charts/chart1.xml", `<c:chartSpace xmlns:c="${CHART_NS}" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><c:chart><c:autoTitleDeleted val="1"/><c:plotArea><c:layout/><c:barChart><c:barDir val="col"/><c:grouping val="clustered"/><c:ser><c:idx val="0"/><c:order val="0"/><c:tx><c:v>STORED CHART</c:v></c:tx><c:cat><c:strRef><c:f>'Cached results'!$A$1:$A$2</c:f><c:strCache><c:ptCount val="2"/><c:pt idx="0"><c:v>Alpha</c:v></c:pt><c:pt idx="1"><c:v>Beta</c:v></c:pt></c:strCache></c:strRef></c:cat><c:val><c:numRef><c:f>'Cached results'!$B$1:$B$2</c:f><c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="2"/><c:pt idx="0"><c:v>73</c:v></c:pt><c:pt idx="1"><c:v>19</c:v></c:pt></c:numCache></c:numRef></c:val></c:ser><c:axId val="1"/><c:axId val="2"/></c:barChart><c:catAx><c:axId val="1"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="b"/><c:crossAx val="2"/><c:crosses val="autoZero"/></c:catAx><c:valAx><c:axId val="2"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="l"/><c:crossAx val="1"/><c:crosses val="autoZero"/></c:valAx></c:plotArea><c:plotVisOnly val="1"/></c:chart></c:chartSpace>`);
  return zip.generateAsync({ type: "nodebuffer" });
}
